

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aleja
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_nuevovehiculo = new javax.swing.JPopupMenu();
        jmi_agregarvehiculo = new javax.swing.JMenuItem();
        jmi_limpiarcasillas = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();
        popup_arbol = new javax.swing.JPopupMenu();
        jmi_agregarfav = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel_nuevovehi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_anio = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        tf_modelo = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_codigo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol_vehiculos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_detalles = new javax.swing.JTable();
        bt_exportar = new javax.swing.JButton();
        cb_favoritos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jmi_agregarvehiculo.setText("Agregar Vehiculo");
        jmi_agregarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarvehiculoActionPerformed(evt);
            }
        });
        popup_nuevovehiculo.add(jmi_agregarvehiculo);

        jmi_limpiarcasillas.setText("Limpiar Casillas");
        jmi_limpiarcasillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_limpiarcasillasActionPerformed(evt);
            }
        });
        popup_nuevovehiculo.add(jmi_limpiarcasillas);

        jmi_salir.setText("Salir\n");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        popup_nuevovehiculo.add(jmi_salir);

        jmi_agregarfav.setText("Agregar a Favoritos\n");
        jmi_agregarfav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarfavActionPerformed(evt);
            }
        });
        popup_arbol.add(jmi_agregarfav);

        jmi_eliminar.setText("Eliminar\n");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        popup_arbol.add(jmi_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        panel_nuevovehi.setForeground(new java.awt.Color(0, 0, 0));
        panel_nuevovehi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_nuevovehiMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nuevo Vehiculo");

        tf_anio.setBackground(new java.awt.Color(255, 255, 255));

        tf_marca.setBackground(new java.awt.Color(255, 255, 255));

        tf_modelo.setBackground(new java.awt.Color(255, 255, 255));

        tf_precio.setBackground(new java.awt.Color(255, 255, 255));

        dc_fecha.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Año");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Marca");

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Modelo");

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha");

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio");

        jl_codigo.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        jl_codigo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Codigo");

        javax.swing.GroupLayout panel_nuevovehiLayout = new javax.swing.GroupLayout(panel_nuevovehi);
        panel_nuevovehi.setLayout(panel_nuevovehiLayout);
        panel_nuevovehiLayout.setHorizontalGroup(
            panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_nuevovehiLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_nuevovehiLayout.createSequentialGroup()
                        .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_marca)
                                .addComponent(tf_modelo)
                                .addComponent(tf_precio)
                                .addComponent(tf_anio)
                                .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_nuevovehiLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)))
                .addGap(34, 34, 34))
            .addGroup(panel_nuevovehiLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jl_codigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_nuevovehiLayout.setVerticalGroup(
            panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nuevovehiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_codigo)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panel_nuevovehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(42, 42, 42))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Vehiculos");
        arbol_vehiculos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol_vehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbol_vehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbol_vehiculos);

        jt_detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Anio", "Marca", "Modelo", "Fecha", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jt_detalles);

        bt_exportar.setBackground(new java.awt.Color(153, 102, 255));
        bt_exportar.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        bt_exportar.setForeground(new java.awt.Color(0, 0, 0));
        bt_exportar.setText("Exportar a txt");
        bt_exportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exportarMouseClicked(evt);
            }
        });

        cb_favoritos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_favoritosItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Inventario");

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Vehiculos Existentes");

        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Favoritos");

        jLabel10.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("Detalle del vehiculo seleccionado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panel_nuevovehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(bt_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_favoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(panel_nuevovehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_favoritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_nuevovehiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_nuevovehiMouseClicked
       if (evt.isMetaDown()){
           popup_nuevovehiculo.show(evt.getComponent(), evt.getX(), evt.getY());
       }
       
    }//GEN-LAST:event_panel_nuevovehiMouseClicked

    private void jmi_limpiarcasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_limpiarcasillasActionPerformed
        tf_anio.setText("");
        tf_marca.setText("");
        tf_modelo.setText("");
        tf_precio.setText("");
        jl_codigo.setText("");
        dc_fecha.setDate(null);
        
    }//GEN-LAST:event_jmi_limpiarcasillasActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void bt_exportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exportarMouseClicked
        DefaultTableModel tabla = (DefaultTableModel) jt_detalles.getModel();
        JFileChooser fc = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Archivos de texto", "txt");
        fc.setFileFilter(filter);
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        if (tabla.getRowCount()>0){
            String temp = "";
        
            for (int j = 0; j < 6; j++) {
                if (j==5){
                    temp+=tabla.getValueAt(0, j);
                    temp+="\n";
                }
                else{
                    temp+=tabla.getValueAt(0, j);
                temp+=";";
                }
            }
            
        int sel = fc.showOpenDialog(this);
        if (sel == JFileChooser.APPROVE_OPTION) {
        //agarrar info de la row en la tabla y escribir eso en el archivo
         archivo = fc.getSelectedFile();
           try {
               fw = new FileWriter(archivo,true);
                bw = new BufferedWriter(fw);
                
                bw.write(temp);
                
                bw.flush();
                bw.close();
                fw.close();
                
           } catch (IOException ex) {
               ex.printStackTrace();
           }
        
        
        }
        JOptionPane.showMessageDialog(this, "Escritura realizada exitosamente");
        
        }
        else {
            JOptionPane.showMessageDialog(this, "La tabla esta vacia");
        }
        
        
    }//GEN-LAST:event_bt_exportarMouseClicked

    private void jmi_agregarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarvehiculoActionPerformed
        Random r = new Random();
        
        
        if (tf_anio.getText().isEmpty() || tf_marca.getText().isEmpty() || tf_modelo.getText().isEmpty() || tf_precio.getText().isEmpty() || dc_fecha==null
                || (tf_anio.getText().isEmpty() && tf_marca.getText().isEmpty() && tf_modelo.getText().isEmpty() && tf_precio.getText().isEmpty() && dc_fecha==null)){
            try {
                throw new Exception("Asegurese de llenar todos los campos");
            } catch (Exception ex) {
               ex.printStackTrace();
            }
        }
        else {
            
            int anio = Integer.parseInt(tf_anio.getText());
            int codigo = r.nextInt(2000)+1000;
            double precio = Double.parseDouble(tf_precio.getText());
            jl_codigo.setText(Integer.toString(codigo));
            int cont = 0;  
            
            Vehiculo v = new Vehiculo(anio, codigo, tf_marca.getText(), tf_modelo.getText(), dc_fecha.getDate(), precio);
            
            DefaultTreeModel arbol = (DefaultTreeModel) arbol_vehiculos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) arbol.getRoot();
            String anioo = tf_anio.getText();
            
                     
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(anioo)) {
                  DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(v);
                  ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodo);
                  cont++;
                }
            }
            
            if (cont == 0) {
                DefaultMutableTreeNode anionuevo = new DefaultMutableTreeNode(anioo);
                DefaultMutableTreeNode nodito = new DefaultMutableTreeNode(v);
                raiz.add(anionuevo);                
                anionuevo.add(nodito);
            }
          arbol.reload();
            
        }
        
    }//GEN-LAST:event_jmi_agregarvehiculoActionPerformed

    private void arbol_vehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbol_vehiculosMouseClicked
        if (evt.isMetaDown()){
            int fila = arbol_vehiculos.getClosestRowForLocation(evt.getX(), evt.getY());
            arbol_vehiculos.setSelectionRow(fila);
            Object temp = arbol_vehiculos.getSelectionPath().getLastPathComponent();
            seleccion = (DefaultMutableTreeNode) temp;
            if (seleccion.getUserObject() instanceof Vehiculo) {
                popup_arbol.show(evt.getComponent(),evt.getX(), evt.getY());
                carrito = (Vehiculo) seleccion.getUserObject();
            }
        }
    }//GEN-LAST:event_arbol_vehiculosMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        DefaultTreeModel arbol = (DefaultTreeModel) arbol_vehiculos.getModel();
        DefaultComboBoxModel combobox = (DefaultComboBoxModel) cb_favoritos.getModel();
        arbol.removeNodeFromParent(seleccion);
        combobox.removeElement(seleccion);
        
        arbol.reload();
        cb_favoritos.setModel(combobox);
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_agregarfavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarfavActionPerformed
        DefaultComboBoxModel combobox = (DefaultComboBoxModel) cb_favoritos.getModel();
        combobox.addElement(carrito);
    }//GEN-LAST:event_jmi_agregarfavActionPerformed

    private void cb_favoritosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_favoritosItemStateChanged
        Vehiculo car = (Vehiculo)cb_favoritos.getSelectedItem();
        DefaultTableModel tabla = (DefaultTableModel) jt_detalles.getModel();
        tabla.setRowCount(0);//limpiar
        String [] arrayDetalles = new String [6];
        DateFormat df =new SimpleDateFormat("dd/MM/yyyy");
        
        arrayDetalles[0] = Integer.toString(car.getCodigo());
        arrayDetalles[1] = Integer.toString(car.getAnio());
        arrayDetalles[2] = car.getMarca();
        arrayDetalles[3] = car.getModelo();
        arrayDetalles[4] = df.format(car.getFecha());
        arrayDetalles[5] = Double.toString(car.getPrecio());
        
        tabla.addRow(arrayDetalles);
        jt_detalles.setModel(tabla);
        
    }//GEN-LAST:event_cb_favoritosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol_vehiculos;
    private javax.swing.JButton bt_exportar;
    private javax.swing.JComboBox<String> cb_favoritos;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JMenuItem jmi_agregarfav;
    private javax.swing.JMenuItem jmi_agregarvehiculo;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_limpiarcasillas;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JTable jt_detalles;
    private javax.swing.JPanel panel_nuevovehi;
    private javax.swing.JPopupMenu popup_arbol;
    private javax.swing.JPopupMenu popup_nuevovehiculo;
    private javax.swing.JTextField tf_anio;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JTextField tf_precio;
    // End of variables declaration//GEN-END:variables
protected DefaultMutableTreeNode seleccion;
protected Vehiculo carrito;
}
